name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  schedule:
    # This will run every other Wednesday at 09:00 UTC
    - cron: '0 9 */14 * 3'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Clean build output
        run: flutter clean

      - name: Get dependencies
        run: flutter pub get

      - name: Build
        run: flutter build web --base-href="/LoLoPedia/" --release

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' || github.event_name == 'schedule' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          push: true
          force: true
          keep_files: false
          